### ISSUE TITLE
Error: CR Apply LoRA Stack: 'dict' object has no attribute 'cond_stage_model'

### ISSUE THREAD

**Issue by mattymatty** [RockOfFire/ComfyUI_Comfyroll_CustomNodes#11]
I am getting the model and clip from ttN pipeLoaderSDXL and putting it into CR Apply LoRA Stack.
I am outputting the model and clip to ttN pipeKSamplerSDXL.

```
Error occurred when executing CR Apply LoRA Stack:

'dict' object has no attribute 'cond_stage_model'

File "C:\Users\NAME\ComfyUI\execution.py", line 151, in recursive_execute
output_data, output_ui = get_output_data(obj, input_data_all)
File "C:\Users\NAME\ComfyUI\execution.py", line 81, in get_output_data
return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
File "C:\Users\NAME\ComfyUI\execution.py", line 74, in map_node_over_list
results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
File "C:\Users\NAME\ComfyUI\custom_nodes\ComfyUI_Comfyroll_CustomNodes\Comfyroll_Nodes.py", line 1042, in apply_lora_stack
model_lora, clip_lora = comfy.sd.load_lora_for_models(model_lora, clip_lora, lora, strength_model, strength_clip)
File "C:\Users\NAME\ComfyUI\comfy\sd.py", line 324, in load_lora_for_models
key_map = comfy.lora.model_lora_keys_clip(clip.cond_stage_model, key_map)
```

**Comment by Suzie1** [comment]
We didn't test this compatibility. I'll test this tomorrow morning and may include a fix in the update tomorrow evening. Thank you for reporting this. Suzie

**Comment by Suzie1** [comment]
Hi, I have tested this and it works ok for me. Have you checked your ComfyUI is up to date? I recommend using the bat file update. Please DM me on AI Revolution if this continues to be a problem. Suzie

**Comment by Suzie1** [comment]
[LoRA stack test.zip](https://github.com/RockOfFire/ComfyUI_Comfyroll_CustomNodes/files/12487070/LoRA.stack.test.zip)

Hi, this is the test that I did. My model locations are slightly different to yours, I have subfolders in models and loras.

**Comment by Suzie1** [comment]
Hello, Is this still an issue for you?

**Comment by Suzie1** [comment]
Closing since there have been no further reports of issues
