### ISSUE TITLE
multiscontrolnet error when using only 1 out of 3 input image slots

### ISSUE THREAD

**Issue by MokkaBoss1** [RockOfFire/ComfyUI_Comfyroll_CustomNodes#12]
Hi, I think I maybe have found another bug when using the multicontrol net stacker. If you leave any image input spaces (e.g. image 2 and / or image 3) empty, you get an error

"Error occurred when executing CR Multi-ControlNet Stack:

Comfyroll_ControlNetStack.controlnet_stacker() missing 2 required positional arguments: 'image_2' and 'image_3'

File "C:\sdxl\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\execution.py", line 151, in recursive_execute
output_data, output_ui = get_output_data(obj, input_data_all)
File "C:\sdxl\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\execution.py", line 81, in get_output_data
return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
File "C:\sdxl\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\execution.py", line 74, in map_node_over_list
results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))"
--------------------------------------------------------------------------------------------------
json file attached (renamed as .txt)
[multicontrolnet stacker error.txt](https://github.com/RockOfFire/ComfyUI_Comfyroll_CustomNodes/files/12453578/multicontrolnet.stacker.error.txt)

**Comment by Suzie1** [comment]
You need to connect an image to all three image inputs even if you are not using them. You can leave the controlnets for image2 and image3 Off, but they must have an input image. You can connect the same image to all three inputs. Suzie

**Comment by MokkaBoss1** [comment]
ok thanks - it's clear

Mokkaboss1

**Comment by Suzie1** [comment]
I'll add something to cover this in the Troubleshooting guide and also on the main post. Thanks for reporting it.
