### ISSUE TITLE
Comfyroll nodes disappeared from the Nodes menu (and unavailable in the workflow)

### ISSUE THREAD

**Issue by alessandroperilli** [RockOfFire/ComfyUI_Comfyroll_CustomNodes#16]
I'm very happy to see that the latest update brings compatibility with LucianoCirino Efficiency nodes. I'm the one that originally asked him to verify the issues I was having. 

However, this new update made the entire Comfyroll suite disappear from the ComfyUI Nodes menu, and all your nodes are red as unavailable inside the workflow.

**Comment by LucianoCirino** [comment]
Can you show what the error is please?

**Comment by Unstable-Reality** [comment]
Sure @LucianoCirino: 

<img width="715" alt="Screenshot 2023-09-02 at 19 04 58" src="https://github.com/RockOfFire/ComfyUI_Comfyroll_CustomNodes/assets/129083997/b081c634-dc7d-4c2f-990b-4368a90052eb">
<img width="1650" alt="Screenshot 2023-09-02 at 19 05 14" src="https://github.com/RockOfFire/ComfyUI_Comfyroll_CustomNodes/assets/129083997/ac5b2acc-cc3a-4ebb-9740-dd3ade1cc9e4">
<img width="319" alt="Screenshot 2023-09-02 at 19 05 26" src="https://github.com/RockOfFire/ComfyUI_Comfyroll_CustomNodes/assets/129083997/4ae70e6b-ba52-4869-99c4-1c9a6b094970">
<img width="1415" alt="Screenshot 2023-09-02 at 19 06 04" src="https://github.com/RockOfFire/ComfyUI_Comfyroll_CustomNodes/assets/129083997/fcc41e49-2d76-47f8-a318-c9a06d3e6d8e">

As you can see, the entire Comfyroll suite disappeared from the menu. This happened after the last commit.

**Comment by alessandroperilli** [comment]
Sure @LucianoCirino:

<img width="715" alt="Screenshot 2023-09-02 at 19 04 58" src="https://github.com/RockOfFire/ComfyUI_Comfyroll_CustomNodes/assets/9775949/9c230bc6-55e0-44f0-a9bd-8531885f2c28">
<img width="1650" alt="Screenshot 2023-09-02 at 19 05 14" src="https://github.com/RockOfFire/ComfyUI_Comfyroll_CustomNodes/assets/9775949/d1a139c6-781f-4b91-9de4-ab14709cd37a">
<img width="319" alt="Screenshot 2023-09-02 at 19 05 26" src="https://github.com/RockOfFire/ComfyUI_Comfyroll_CustomNodes/assets/9775949/685be6db-353a-4b2e-97c2-25584f90562f">
<img width="1415" alt="Screenshot 2023-09-02 at 19 06 04" src="https://github.com/RockOfFire/ComfyUI_Comfyroll_CustomNodes/assets/9775949/15936a0c-bb3c-4f3d-9ab5-7c5ac52dca3c">

As you can see, the entire Comfyroll suite disappeared from the Node menu, even if it's installed in the system.

I even tried disabling and re-enabling it.

**Comment by alessandroperilli** [comment]
Fixed. Thank you.
