### ISSUE TITLE
A good way to avoid warning "Setuptools is replacing distutils"

### ISSUE THREAD

**Issue by Layer-norm** [RockOfFire/ComfyUI_Comfyroll_CustomNodes#21]
If you import pip in you python code it may cause "Setuptools is replacing distutils" warning, which may delete the whole distutils module. Because distutils was imported before Setuptools, but importing Setuptools also replaces the distutils and calls the function clear_distutils() in "/site-packages/_distutils_hack/__init__.py" to initialize. In other words, if some customnodes that requires distutils module is loaded before comfyroll, some errors may occur.
```python
#code from   /site-packages/_distutils_hack/__init__.py
def clear_distutils():
    if 'distutils' not in sys.modules:
        return
    import warnings

    warnings.warn("Setuptools is replacing distutils.")
    mods = [
        name
        for name in sys.modules
        if name == "distutils" or name.startswith("distutils.")
    ]
    for name in mods:
        del sys.modules[name]
``` 
A good way to avoid this warning is delete all the  unnecessary "import pip", and put it into exception if needed.
for exanple in Comfyroll_Nodes.py, delete line 14 first and add "import pip" in line 32
```python
import torch
import numpy as np
import os
import sys
import io
from PIL import Image, ImageEnhance
from PIL.PngImagePlugin import PngInfo
# import json
``` 
```python
try:
    import matplotlib.pyplot as plt
except ImportError:
    import pip
    pip.main(['install', 'matplotlib'])
    import matplotlib.pyplot as plt
``` 
before:
![before 2023-09-30 185216](https://github.com/RockOfFire/ComfyUI_Comfyroll_CustomNodes/assets/140777998/1620379f-3302-4e03-9437-335936a1a7b4)
after:
![after 2023-09-30 190255](https://github.com/RockOfFire/ComfyUI_Comfyroll_CustomNodes/assets/140777998/78536ccc-fcf7-41bb-a765-bbb4ee5bcddd)

**Comment by RockOfFire** [comment]
You have a really good point!  That's a really good idea.  I'll implement that here and in the next release that will be in place.

**Comment by RockOfFire** [comment]
Thank you for helping us out with a fix for this!  :D  Let me know if you continue to see the issue.

**Comment by Layer-norm** [comment]
It works 👍
