### ISSUE TITLE
CR XY From Folder

### ISSUE THREAD

**Issue by DommDynamite** [RockOfFire/ComfyUI_Comfyroll_CustomNodes#22]
image_folder is always undefined. Is there any documentation on how these nodes are expected to be set up?

**Comment by Suzie1** [comment]
Hello, another user reported this issue too.
I was planning an update this weekend to fix the outstanding issues, but unfortunately I got sick, so the update will probably be on Monday or Tuesday.
Sorry, there is no documentation other than the CIVitAI post
https://civitai.com/models/159165/comfyui-xy-grid-demos-xy-anything
The demos are designed as mini-tutorials. I will be adding more soon.
There is also a video that will be coming out next week (Grockster is making one for me).

**Comment by Suzie1** [comment]
i just checked on the undefined folder, you can resolve that issue by creating the subfolder in the ComfyUI\output folder 9e.g. ComfyUI\output\Test1) and then refreshing the workflow

**Comment by Suzie1** [comment]
Hi, I did the update to the nodes, and the video is available now. I will be updating the CivitAI post today.
Here is the video link:
https://www.youtube.com/watch?v=81R8mgYhq_k
I checked with another user that had the undefined error, and he confirmed that adding the subfolder resolved the issue.
If you are still having still having problems, please DM me on the AI revolution discord server.

**Comment by Suzie1** [comment]
closing now, let us know if you have any further problems, Suzie
