### ISSUE TITLE
not found: CR Batch Process Switch

### ISSUE THREAD

**Issue by msskaa12** [RockOfFire/ComfyUI_Comfyroll_CustomNodes#23]
after install this node , I restart comfyUI, It comes error : 

When loading the graph, the following node types were not found:
CR Batch Process Switch
Nodes that have failed to load will show as red on the graph.
_____
I attach a screenshot that is  infomation in my terminal :

__
os: ubuntu 20.04
![new](https://github.com/RockOfFire/ComfyUI_Comfyroll_CustomNodes/assets/78275037/e4b26279-ac5b-43de-8ffd-9b8f4fbd6dec)

**Comment by Suzie1** [comment]
hi, thanks for reporting this, i'll test it now

**Comment by Suzie1** [comment]
Hello, I did a quick test and couldn't find an error. It looks as though the nodes are failing on loading.
The log message above doesn't give enough detail to identify the cause of the failure. Are there any other error messages in the log that mention comfyroll? Also, is your ComfyUI install up to date?

**Comment by msskaa12** [comment]
> Hello, I did a quick test and couldn't find an error. It looks as though the nodes are failing on loading. The log message above doesn't give enough detail to identify the cause of the failure. Are there any other error messages in the log that mention comfyroll? Also, is your ComfyUI install up to date?

thanks for reply,  you can use this file to try my work flow :
https://github.com/nerdyrodent/AVeryComfyNerd/blob/main/Reposer.png


bellow is my working progress
1 open this file in comfyui ,  it comes not found: CR Batch Process Switch
2 after I chose model ,and click the "queque prompt" , error message popup: SyntaxError: Unexpected non-whitespace character after JSON at position 4 (line 1 column 5)
3 I  had go to check the comfyui Manager to install missing custom node , it seems installed ,but still appear at missing list.I had try to reinstall ComfyUI_Comfyroll_CustomNodes , and restart comfyui , the error is comes again. 
![new3](https://github.com/RockOfFire/ComfyUI_Comfyroll_CustomNodes/assets/78275037/3d3a0cbd-78fe-4a41-afa1-03090adf9b49)
![new2](https://github.com/RockOfFire/ComfyUI_Comfyroll_CustomNodes/assets/78275037/56e26c65-abf7-4fb9-be51-223a83932614)
![e722d150-23a9-4129-8cec-078425bb2276](https://github.com/RockOfFire/ComfyUI_Comfyroll_CustomNodes/assets/78275037/10948c82-e138-47cc-8c42-775399b36260)

here is the message in terminal 
![new1](https://github.com/RockOfFire/ComfyUI_Comfyroll_CustomNodes/assets/78275037/cfecdbad-6c7d-4203-b787-7abca03237dc)

here is my conda enviroment
![Screenshot from 2023-10-19 14-40-10](https://github.com/RockOfFire/ComfyUI_Comfyroll_CustomNodes/assets/78275037/ea163ab8-a995-4140-922e-68f20bac5d94)

**Comment by Suzie1** [comment]
Hello, both RockyOfFire and myself looked at this and we couldn't see anything in the error message that can help us triage the issue. Normally error messages will mention the node pack or node that is causing the error. In this case the error appears to originate from the node class mappings, but from our tests we cannot see any problems with the Comfyroll init file.

I note the you are using python 3.8 which is quite an old version. ComfyUI supports up to 3.11.

There is another node that you could use as a replacement for the Batch Process Switch if this is the only node that you need from Comfyroll. This is the Latent Input Switch node in WAS nodes.

You would be welcome to DM me on AI revolution discord if you need more assistance on this.
Suzie

**Comment by msskaa12** [comment]
appreciate your reply ,  I will try to update  latest  python.

**Comment by msskaa12** [comment]
> Hello, both RockyOfFire and myself looked at this and we couldn't see anything in the error message that can help us triage the issue. Normally error messages will mention the node pack or node that is causing the error. In this case the error appears to originate from the node class mappings, but from our tests we cannot see any problems with the Comfyroll init file.
> 
> I note the you are using python 3.8 which is quite an old version. ComfyUI supports up to 3.11.
> 
> There is another node that you could use as a replacement for the Batch Process Switch if this is the only node that you need from Comfyroll. This is the Latent Input Switch node in WAS nodes.
> 
> You would be welcome to DM me on AI revolution discord if you need more assistance on this. Suzie

I had update to python3.10 ,it works , thanks
