### ISSUE TITLE
since last update import failed 

### ISSUE THREAD

**Issue by Autantpourmoi** [RockOfFire/ComfyUI_Comfyroll_CustomNodes#34]
hi, since last update import failed at every start of Comfy ui , tried to uninstall reinstall with the same results , also update comfy but no changes

**Comment by plaidam** [comment]
Me too. Tried to get to install using both ComfyUI manager and git clone but ran into the same error.

**Comment by Autantpourmoi** [comment]
> Me too. Tried to get to install using both ComfyUI manager and git clone but ran into the same error.

same to me , tried git clone and manager , i'm using it with mac osx

**Comment by plaidam** [comment]
mac os as well.

**Comment by Autantpourmoi** [comment]
> mac os as well.

this fix it for me 
https://github.com/RockOfFire/ComfyUI_Comfyroll_CustomNodes/issues/35

**Comment by Suzie1** [comment]
Hi, apolgies I have been away on holiday for two weeks. Please can you send me the error message that you get. Suzie

**Comment by Suzie1** [comment]
The Arabic Text node has been removed now. Please can you retry.

**Comment by Suzie1** [comment]
Closing. Please re-open if the issues recurs. Suzie
