### ISSUE TITLE
IMPORT FAILED after Updating

### ISSUE THREAD

**Issue by budihartono** [RockOfFire/ComfyUI_Comfyroll_CustomNodes#35]
Hello, I just updated the module and got this error.

`   0.0 seconds (IMPORT FAILED): /AI Systems/comfyui/ComfyUI/custom_nodes/ComfyUI_Comfyroll_CustomNodes`

The exception is like below:
```
Traceback (most recent call last):
  File "/Volumes/ADATA SU 650 Media/AI Systems/comfyui/ComfyUI/nodes.py", line 1735, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Volumes/ADATA SU 650 Media/AI Systems/comfyui/ComfyUI/custom_nodes/ComfyUI_Comfyroll_CustomNodes/__init__.py", line 14, in <module>
    from .nodes.pil_text import *
  File "/Volumes/ADATA SU 650 Media/AI Systems/comfyui/ComfyUI/custom_nodes/ComfyUI_Comfyroll_CustomNodes/nodes/pil_text.py", line 22, in <module>
    subprocess.check_call(['python', '-m', 'pip', 'install', 'python_bidi'])
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 408, in check_call
    retcode = call(*popenargs, **kwargs)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 389, in call
    with Popen(*popenargs, **kwargs) as p:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 1950, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'python'
```

I use Python3.11, so I use the command `python3`. I managed to fix it by changing the code in the `pil_text.py` like below:
```
try:
    from bidi.algorithm import get_display
except ImportError:
    import subprocess
    subprocess.check_call(['python3', '-m', 'pip', 'install', 'python_bidi'])

try:    
    import arabic_reshaper    
except ImportError:
    import subprocess
    subprocess.check_call(['python3', '-m', 'pip', 'install', 'arabic_reshaper'])
```

Hopefully, this can be fixed in the next update.

**Comment by Autantpourmoi** [comment]
> Hello, I just updated the module and got this error.
> 
> ` 0.0 seconds (IMPORT FAILED): /AI Systems/comfyui/ComfyUI/custom_nodes/ComfyUI_Comfyroll_CustomNodes`
> 
> The exception is like below:
> 
> ```
> Traceback (most recent call last):
>   File "/Volumes/ADATA SU 650 Media/AI Systems/comfyui/ComfyUI/nodes.py", line 1735, in load_custom_node
>     module_spec.loader.exec_module(module)
>   File "<frozen importlib._bootstrap_external>", line 940, in exec_module
>   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
>   File "/Volumes/ADATA SU 650 Media/AI Systems/comfyui/ComfyUI/custom_nodes/ComfyUI_Comfyroll_CustomNodes/__init__.py", line 14, in <module>
>     from .nodes.pil_text import *
>   File "/Volumes/ADATA SU 650 Media/AI Systems/comfyui/ComfyUI/custom_nodes/ComfyUI_Comfyroll_CustomNodes/nodes/pil_text.py", line 22, in <module>
>     subprocess.check_call(['python', '-m', 'pip', 'install', 'python_bidi'])
>   File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 408, in check_call
>     retcode = call(*popenargs, **kwargs)
>               ^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 389, in call
>     with Popen(*popenargs, **kwargs) as p:
>          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 1026, in __init__
>     self._execute_child(args, executable, preexec_fn, close_fds,
>   File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 1950, in _execute_child
>     raise child_exception_type(errno_num, err_msg, err_filename)
> FileNotFoundError: [Errno 2] No such file or directory: 'python'
> ```
> 
> I use Python3.11, so I use the command `python3`. I managed to fix it by changing the code in the `pil_text.py` like below:
> 
> ```
> try:
>     from bidi.algorithm import get_display
> except ImportError:
>     import subprocess
>     subprocess.check_call(['python3', '-m', 'pip', 'install', 'python_bidi'])
> 
> try:    
>     import arabic_reshaper    
> except ImportError:
>     import subprocess
>     subprocess.check_call(['python3', '-m', 'pip', 'install', 'arabic_reshaper'])
> ```
> 
> Hopefully, this can be fixed in the next update.

Work for me , thanks a lot >>>

**Comment by Suzie1** [comment]
Hi, my apolgies the Arabic Text node appears to be causing problems with the imports on some builds. In your case it can't find python to do the install. I'll temporarily remove the node until I find a better solution.

**Comment by Suzie1** [comment]
The Arabic Text node has been removed now. Please can you retry.

**Comment by Suzie1** [comment]
Closing. Please re-open if the issues recurs. Suzie
