### ISSUE TITLE
Not found: CR Batch Process Switch

### ISSUE THREAD

**Issue by jennyleung** [RockOfFire/ComfyUI_Comfyroll_CustomNodes#36]
Hi there, 

I I saw another issue with this name, trying to use the same workflow. Unfortunately, updating Python did not work for me (I'm on 3.11.6). 

Here's an image of my terminal. 
<img width="1157" alt="image" src="https://github.com/RockOfFire/ComfyUI_Comfyroll_CustomNodes/assets/7319757/5d915f06-1c0e-4e58-aa51-5e2792bf2cae">

**Comment by Suzie1** [comment]
Hi, my apolgies the Arabic Text node appears to be causing problems with the imports on some builds. In your case it can't find python to do the install. I'll temporarily remove the node until I find a better solution.

**Comment by Suzie1** [comment]
The Arabic Text node has been removed now. Please can you retry.

**Comment by Suzie1** [comment]
Closing. Please re-open if the issues recurs. Suzie
