### ISSUE TITLE
[FEATURE] Output cktp_name from the CR_SelectModel

### ISSUE THREAD

**Issue by sh1ny** [RockOfFire/ComfyUI_Comfyroll_CustomNodes#43]
Hey, a small feature request:

On the select model node, can we have an output that exposes the cktp_name of the loaded model in addition to the model output ?
It's to have compatibility with some nodes like rgthree's context and SDParameterSaver.

**Comment by sh1ny** [comment]
Here's a screenshot of the nodes and how they interact:

https://i.imgur.com/ONwudoW.png

**Comment by Suzie1** [comment]
yes, thats a good idea, i'll add in the next update
thank you, Suzie

**Comment by Suzie1** [comment]
Hi, its live on github now, please can you check it

**Comment by sh1ny** [comment]
Hey,

It seems the ckpt_name is of type text and rgthree's switch requires combo type ?
I can't connect it to either context big nor sd prompt saver:

https://i.imgur.com/UsKRBxe.png

**Comment by Suzie1** [comment]
Hello, yes the type on ckpt_name is STRING. You can convert this to a combo using CR String To Combo.
I don't think it is a good idea to make the ckpt_name an ANY type. ANY is required when connecting to COMBO widgets.
please feel free to contact me on AI Revolution or Comfy UI Workflow Dev if you want to discuss in more detail.
Suzie
