### ISSUE TITLE
Not really an issue, More of a Question

### ISSUE THREAD

**Issue by AIMusicExperiment** [RockOfFire/ComfyUI_Comfyroll_CustomNodes#5]
Dear Mr. or Ms. Comfyroll, Rock of Fire person,

I am developing a custom workflow based on the Deforum Extension in A1111. As you can guess it is not easy. I have one challenge that I've not yet solved and that is changing prompts based on the frame number. It is easy enough to get the frame from the sequence loader that I'm using, but I'm not sure of the best way to change prompts. I think that your conditioning switch will likely be part of the solution. You have proven to be way more knowledgeable than I with these things; have you figured out a way to do this? Thanks in advice for any help you can offer!

**Comment by Suzie1** [comment]
Hi, Ms Comfyroll here,

How many prompts are you likely to need? For example between 5 and 20?
This would help suggest a node design. If you need a separate node for the prompts we might be able to help make it for you.

You are welcome to DM us via the AI Revolution discord.

many cats
Suzie
