### ISSUE TITLE
CR String to Combo node possibly causing an error

### ISSUE THREAD

**Issue by EricRollei** [RockOfFire/ComfyUI_Comfyroll_CustomNodes#57]
Hello,
I've been using the CR String to Combo node with the CR Text input switch to load both checkpoints and Lora from both list boxes and also saved files.  I pass the checkpoint name or Lora name to their respective loaders using the CR string to combo node.  I do this because I can't connect the text line directly to the loaders.  Today after updating, I started to get errors.  Oddly I'm not getting a console or pop-up error report, however from debugging, I can see that the load text line from file, load line from list and CR Text input switches are working so it appears the error is in the CR String to Combo node.  Also I note that in this update a show_help connection also appeared if that is helpful to determine what update the problem occurred with.

![image](https://github.com/RockOfFire/ComfyUI_Comfyroll_CustomNodes/assets/97568200/5b7851ae-995c-4b09-88b7-cda7d32064ae)

![image](https://github.com/RockOfFire/ComfyUI_Comfyroll_CustomNodes/assets/97568200/3630104b-6694-4c5b-a3d9-7e01b02f45c5)

**Comment by RockOfFire** [comment]
Thank you for seeing this issue!  It has been fixed now.  There was a PR request as well.
