### ISSUE TITLE
New LORAs are not detected automatically

### ISSUE THREAD

**Issue by oxysoft** [RockOfFire/ComfyUI_Comfyroll_CustomNodes#6]
The built-in LORA loader node detects new LORAs dynamically without restarting the server, although it does require a page refresh. Do you think we could make it the same? (or even better, no page refresh)

Cheers, very useful nodes here

**Comment by Suzie1** [comment]
Hi, I'll look at this today. Thank you for reporting it. Suzie

**Comment by Suzie1** [comment]
Hi, I have a fix now. it will be deployed at the weekend. Thanks again. Suzie
