### ISSUE TITLE
multi-controlnet stack

### ISSUE THREAD

**Issue by MokkaBoss1** [RockOfFire/ComfyUI_Comfyroll_CustomNodes#8]
Hi,

I noticed an issue with the multicontrolnet stacker this morning - pretty sure it was working Yesterday so I think a bug must have crept in with the last update.

[workflow (34).txt](https://github.com/RockOfFire/ComfyUI_Comfyroll_CustomNodes/files/12445055/workflow.34.txt)

just rename to .json

**Comment by p0mad** [comment]
Same here!
@RockOfFire 
@Suzie1 
@Mikerhinos

**Comment by Suzie1** [comment]
Hello, sorry about that, we'll check it and do a quick update this afternoon if we can find the issue, Suzie

**Comment by MokkaBoss1** [comment]
hope its not me making a silly mistake.

**Comment by Suzie1** [comment]
It looks like the latest update to ComfyUI broke some aspects of ControlNet for SDXL. It also appears to have broken some nodes and node packs. I'm guessing this was an update for the new ControlNet LoRAs. I'm trying to find a solution.

**Comment by Suzie1** [comment]
We found a fix. Comfy moved controlnet to a new file so we needed a new import. We will update the nodes today. Sorry for the inconvenience! Suzie

**Comment by MokkaBoss1** [comment]
Great!! many thanks for the super fast resolution :-)

**Comment by MokkaBoss1** [comment]
thanks again.
